---
- name: "CliXX DB Deployment Ansible Playbook"
  hosts: localhost
  connection: local
  vars:
    instance_id: wordpressdbclixxjenkins
    db_snapshot: wordpressdbclixxsnap
    security_group: sg-0029e71213e91bfff

  tasks:
    - name: Restore DB from snapshot
      amazon.aws.rds_instance:
        state: present
        creation_source: snapshot
        db_instance_identifier: "{{ instance_id }}"
        db_snapshot_identifier: "{{ db_snapshot }}"
        engine: mysql
        db_instance_class: db.t3.medium
        region: us-east-1
        wait: yes
        wait_timeout: 1200

    - name: Modify to add Security Group
      amazon.aws.rds_instance:
        state: present
        db_instance_identifier: "{{ instance_id }}"
        vpc_security_group_ids: 
          - "{{ security_group }}"
        region: us-east-1
        apply_immediately: yes
